### ISSUE TITLE
Error in Nautilus (and other applications too)

### ISSUE THREAD

**Issue by zencubic** [B00merang-Project/macOS-High-Sierra-Dark#5]
When you hover the left sidebar the entrys get a background that don't fit (look at the screenshot).
![screenshot](https://user-images.githubusercontent.com/27775731/38111367-0311364e-339f-11e8-964d-b2510931e854.png)
Gnome Version: 3.28.0
Could you please fix it?
Thanks in advance

**Comment by Elbullazul** [comment]
Thanks for reporting this, will install a 18.04 vm and push fixes when available
