### ISSUE TITLE
While Colored Status bar

### ISSUE THREAD

**Issue by HassanMirza01** [B00merang-Project/macOS-High-Sierra-Dark#6]
i installed this theme on Unity 7.5 installed on Ubuntu 18.04, all worked well except statusbar color, its white instead of black and looks damn ugly, then i tried to use it on gnome on 18.04 and it worked well and status bar was black too... have a look at it :)

**Comment by Elbullazul** [comment]
Can you post a screenshot illustrating the issue?

**Comment by HassanMirza01** [comment]
really sorry bro, am back on Ubuntu 16.04 LTS after messing with everything on bionic nd not able to achieve what i want... i want close, minimize and maximize buttons merged with corner above for easy close apps, 

The issue is all theme work fine, but status bar or top bar in every screen is white, fully white,

**Comment by Elbullazul** [comment]
so the unity panel is white in the dark theme?

**Comment by HassanMirza01** [comment]
Yes... Dock is finw, just top panal is white in dark theme.... It seems unity 7.5 issue... On 7.4.5 it works well on xenial...

**Comment by HassanMirza01** [comment]
This is fixed but color looks weird now...

![image](https://user-images.githubusercontent.com/26677817/40221685-2241ca42-5a4b-11e8-8fa6-8aab4d1ab88f.png)

**Comment by Elbullazul** [comment]
that's how it's supposed to be. macOS Dark panel is pitch black, except with transparency. You can enable that in the Unity Tweak Tool.
